# open this up so we can check available plugins before authenticating
hawtio.plugin=bypass
# open this up so that permissions can validated by anyone
org.apache.karaf.security.jmx=bypass
io.fabric8.cxf;getAddress=bypass
io.fabric8.cxf;getState=bypass
io.fabric8.cxf;getServletContext=bypass
io.fabric8.cxf;isWADL=bypass
io.fabric8.cxf;isWSDL=bypass
io.fabric8.cxf;isSwagger=bypass
org.apache.activemq.Broker;getBrokerVersion=bypass
